### PR TITLE
remove puppetlabs pcci, travisCI does them now

### PR DESCRIPTION
**Pull request by tphoney**

### CODE REVIEW

**Comment by tphoney** [comment]
@bastelfreak wow that was quick. i was typing the following  
"Apologies if i have got this wrong, i am trying to remove these repos from the pcci testing that is currently being run on github. These modules run the acceptance tests under TravisCI, so this is ru ...."

**Comment by bastelfreak** [comment]
I noticed your changed in the past. We're currently doing the same since travis supports docker \o/

**Comment by tphoney** [comment]
@bastelfreak is there any other changes i should make around this ?

**Comment by bastelfreak** [comment]
that should be fine I think. I just need to checkout this repo on our PCCI box

**Comment by tphoney** [comment]
cool !

**Comment by bastelfreak** [comment]
@tphoney I updated our PCCI box, everything should be fine.

**Comment by tphoney** [comment]
Thanks !!

**Pull request merged**
